language: python

matrix:
    include:
        - os: linux
          python: 2.7
        - os: linux
          python: 3.3
        - os: linux
          python: 3.4
        - os: linux
          python: 3.5
        - os: linux
          python: 3.6
        - os: linux
          python: 3.7
          env: RUN_FLAKE=1

cache:
  - pip

install:
  - pip install flake8

script:
  - which python
  - python setup.py install
  - dressing --version
  - dressing c printf
  - dressing -v c printf
  - if [[ $RUN_FLAKE ]]; then flake8 .; fi